services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stat

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
